import { Rule } from 'rc-field-form/lib/interface';

type FormItemType = 'input' | 'select' | 'treeSelect' | 'datePicker' | 'timePicker' | undefined;

export interface FieldOptions {
  value: string;
  label: string;
  children?: FieldOptions[];
  [key: string]: any;
}

// Generated by https://quicktype.io

export interface FormItemConfig {
  id: number;
  dynamicId: number;
  columnType: number;
  fieldName: string;
  fieldContent: string;
  fieldType: string;
  fieldDisplay: number;
  fieldCode: string;
  fieldSelect: number;
  selectMode: string;
  fieldHref: string;
  fieldTitle: string;
  fieldSum: number;
  defaultValue: string;
  fieldUnit: string;
  fieldDataAuthority: string;
  columnConfig: string;
  sort: number;
  fieldSort: number;
  fieldSortName: string;
  fieldRow: string;
  fieldAggregation: string;
  fieldStrategy: string;
  fieldOperate: string;
  tableFiledType: string;
  operateStyle: string;
  options: any;
}
